// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID   uuid.UUID
	Name string
}

type Set struct {
	ID          uuid.UUID
	VideoID     string
	Title       string
	DjName      string
	ChannelName sql.NullString
	Url         string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SetCategory struct {
	SetID      uuid.UUID
	CategoryID uuid.UUID
}

type Track struct {
	ID             uuid.UUID
	SetID          uuid.UUID
	SongName       string
	Artist         sql.NullString
	TimestampInSet sql.NullInt32
	Position       int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
