// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package repository

import (
	"context"
)

const getSetsByCategory = `-- name: GetSetsByCategory :many
SELECT sets.id, sets.video_id, sets.title, sets.dj_name, sets.channel_name, sets.url, sets.created_at, sets.updated_at FROM sets
JOIN set_categories ON sets.id = set_categories.set_id
JOIN categories ON set_categories.category_id = categories.id 
WHERE categories.name ILIKE '%' || $1::text || '%'
`

func (q *Queries) GetSetsByCategory(ctx context.Context, dollar_1 string) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getSetsByCategory, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.DjName,
			&i.ChannelName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetsByChannelName = `-- name: GetSetsByChannelName :many
SELECT id, video_id, title, dj_name, channel_name, url, created_at, updated_at FROM sets WHERE channel_name ILIKE '%' || $1::text || '%'
`

func (q *Queries) GetSetsByChannelName(ctx context.Context, dollar_1 string) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getSetsByChannelName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.DjName,
			&i.ChannelName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetsByDjName = `-- name: GetSetsByDjName :many
SELECT id, video_id, title, dj_name, channel_name, url, created_at, updated_at FROM sets WHERE dj_name ILIKE '%' || $1::text || '%'
`

func (q *Queries) GetSetsByDjName(ctx context.Context, dollar_1 string) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getSetsByDjName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.DjName,
			&i.ChannelName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetsByTitle = `-- name: GetSetsByTitle :many
SELECT id, video_id, title, dj_name, channel_name, url, created_at, updated_at FROM sets WHERE title ILIKE '%' || $1::text || '%'
`

func (q *Queries) GetSetsByTitle(ctx context.Context, dollar_1 string) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getSetsByTitle, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.DjName,
			&i.ChannelName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
