// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: set_categories.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addCategoryToSet = `-- name: AddCategoryToSet :exec
INSERT INTO set_categories (set_id, category_id)
VALUES ($1, $2)
`

type AddCategoryToSetParams struct {
	SetID      uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) AddCategoryToSet(ctx context.Context, arg AddCategoryToSetParams) error {
	_, err := q.db.ExecContext(ctx, addCategoryToSet, arg.SetID, arg.CategoryID)
	return err
}

const getAllCategoriesForSet = `-- name: GetAllCategoriesForSet :many
SELECT categories.id, categories.name FROM set_categories JOIN categories ON
set_categories.category_id = categories.id WHERE set_categories.set_id = $1
`

func (q *Queries) GetAllCategoriesForSet(ctx context.Context, setID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategoriesForSet, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCategoryFromSet = `-- name: RemoveCategoryFromSet :exec
DELETE FROM set_categories WHERE set_id = $1 AND category_id = $2
`

type RemoveCategoryFromSetParams struct {
	SetID      uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) RemoveCategoryFromSet(ctx context.Context, arg RemoveCategoryFromSetParams) error {
	_, err := q.db.ExecContext(ctx, removeCategoryFromSet, arg.SetID, arg.CategoryID)
	return err
}
