// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sets.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createSet = `-- name: CreateSet :one
INSERT INTO sets (id, video_id, title, dj_name, channel_name, url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, video_id, title, dj_name, channel_name, url, created_at, updated_at
`

type CreateSetParams struct {
	ID          uuid.UUID
	VideoID     string
	Title       string
	DjName      string
	ChannelName string
	Url         string
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Set, error) {
	row := q.db.QueryRowContext(ctx, createSet,
		arg.ID,
		arg.VideoID,
		arg.Title,
		arg.DjName,
		arg.ChannelName,
		arg.Url,
	)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.DjName,
		&i.ChannelName,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSetById = `-- name: DeleteSetById :one
Delete FROM sets WHERE id=$1
RETURNING id, video_id, title, dj_name, channel_name, url, created_at, updated_at
`

func (q *Queries) DeleteSetById(ctx context.Context, id uuid.UUID) (Set, error) {
	row := q.db.QueryRowContext(ctx, deleteSetById, id)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.DjName,
		&i.ChannelName,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllSets = `-- name: GetAllSets :many
SELECT id, video_id, title, dj_name, channel_name, url, created_at, updated_at FROM sets
`

func (q *Queries) GetAllSets(ctx context.Context) ([]Set, error) {
	rows, err := q.db.QueryContext(ctx, getAllSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.DjName,
			&i.ChannelName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetById = `-- name: GetSetById :one
SELECT id, video_id, title, dj_name, channel_name, url, created_at, updated_at FROM sets WHERE id=$1
`

func (q *Queries) GetSetById(ctx context.Context, id uuid.UUID) (Set, error) {
	row := q.db.QueryRowContext(ctx, getSetById, id)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.DjName,
		&i.ChannelName,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
