// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (id, set_id, song_name, artist, timestamp_in_set, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, set_id, song_name, artist, timestamp_in_set, position, created_at, updated_at
`

type CreateTrackParams struct {
	ID             uuid.UUID
	SetID          uuid.UUID
	SongName       string
	Artist         sql.NullString
	TimestampInSet sql.NullInt32
	Position       int32
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, createTrack,
		arg.ID,
		arg.SetID,
		arg.SongName,
		arg.Artist,
		arg.TimestampInSet,
		arg.Position,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.SongName,
		&i.Artist,
		&i.TimestampInSet,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrackFromSet = `-- name: DeleteTrackFromSet :one
DELETE FROM tracks WHERE id = $1
RETURNING id, set_id, song_name, artist, timestamp_in_set, position, created_at, updated_at
`

func (q *Queries) DeleteTrackFromSet(ctx context.Context, id uuid.UUID) (Track, error) {
	row := q.db.QueryRowContext(ctx, deleteTrackFromSet, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.SongName,
		&i.Artist,
		&i.TimestampInSet,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTracksForSet = `-- name: GetTracksForSet :many
SELECT id, set_id, song_name, artist, timestamp_in_set, position, created_at, updated_at FROM tracks WHERE set_id = $1
`

func (q *Queries) GetTracksForSet(ctx context.Context, setID uuid.UUID) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, getTracksForSet, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.SongName,
			&i.Artist,
			&i.TimestampInSet,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
