name: Github AWS OIDC
on:
  push:
    branches: [main]

# Need ID token write permission to use OIDC
permissions:
  id-token: write
  contents: read
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}